# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='common.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0c\x63ommon.proto\x12\x02pb\"C\n\x08\x65rr_desc\x12\x0c\n\x04\x43ode\x18\x01 \x01(\x05\x12\x0c\n\x04Type\x18\x02 \x01(\x05\x12\x0b\n\x03Msg\x18\x03 \x01(\t\x12\x0e\n\x06UsrMsg\x18\x04 \x01(\tb\x06proto3')
)




_ERR_DESC = _descriptor.Descriptor(
  name='err_desc',
  full_name='pb.err_desc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='pb.err_desc.Code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Type', full_name='pb.err_desc.Type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Msg', full_name='pb.err_desc.Msg', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UsrMsg', full_name='pb.err_desc.UsrMsg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['err_desc'] = _ERR_DESC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

err_desc = _reflection.GeneratedProtocolMessageType('err_desc', (_message.Message,), dict(
  DESCRIPTOR = _ERR_DESC,
  __module__ = 'common_pb2'
  # @@protoc_insertion_point(class_scope:pb.err_desc)
  ))
_sym_db.RegisterMessage(err_desc)


# @@protoc_insertion_point(module_scope)
