# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import eff_upload_pb2 as eff__upload__pb2


class effUploadStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConfig = channel.unary_unary(
        '/pb.effUpload/GetConfig',
        request_serializer=eff__upload__pb2.config_capture_request.SerializeToString,
        response_deserializer=eff__upload__pb2.config_capture_response.FromString,
        )
    self.Upload = channel.unary_unary(
        '/pb.effUpload/Upload',
        request_serializer=eff__upload__pb2.upload_request.SerializeToString,
        response_deserializer=eff__upload__pb2.upload_response.FromString,
        )
    self.Upload2 = channel.unary_unary(
        '/pb.effUpload/Upload2',
        request_serializer=eff__upload__pb2.upload_request.SerializeToString,
        response_deserializer=eff__upload__pb2.upload_response.FromString,
        )


class effUploadServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Upload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Upload2(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_effUploadServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConfig': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfig,
          request_deserializer=eff__upload__pb2.config_capture_request.FromString,
          response_serializer=eff__upload__pb2.config_capture_response.SerializeToString,
      ),
      'Upload': grpc.unary_unary_rpc_method_handler(
          servicer.Upload,
          request_deserializer=eff__upload__pb2.upload_request.FromString,
          response_serializer=eff__upload__pb2.upload_response.SerializeToString,
      ),
      'Upload2': grpc.unary_unary_rpc_method_handler(
          servicer.Upload2,
          request_deserializer=eff__upload__pb2.upload_request.FromString,
          response_serializer=eff__upload__pb2.upload_response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'pb.effUpload', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
